# 表1:不同特征，不同网络顺序构表

In [216]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [217]:
AUC = np.array(pd.read_csv("out/All_Parameter.csv").iloc[:,-1])
name = np.array(pd.read_csv("out/All_Parameter.csv").iloc[:,0])

In [218]:
def get_normal_avg(x):
    n = 0 
    sum_x = 0
    for i in x:
        if i>0.55:
            n+=1
            sum_x+=i
    return sum_x/n

In [219]:
#对KFold取均值
name_no_fold = []
AUC_no_fold = []
for i in range(len(name)):
    if i%5==0:
        AUC_no_fold.append(get_normal_avg(AUC[i:i+5]))
        name_no_fold.append(name[i])

In [220]:
data = np.zeros(len(AUC_no_fold)).reshape(9,-1)
for i in range(9):
    for j in range(12):
        data[i][3*j] = AUC_no_fold[27*j+3*i]
        data[i][3*j+1] = AUC_no_fold[27*j+3*i+1]
        data[i][3*j+2] = AUC_no_fold[27*j+3*i+2]

In [221]:
data

array([[0.78838817, 0.80826815, 0.78285231, 0.78010394, 0.80342548,
        0.76815927, 0.7618227 , 0.78399216, 0.75871705, 0.84136662,
        0.83991369, 0.83693945, 0.72943121, 0.74107235, 0.71997396,
        0.75141061, 0.76748734, 0.74807504, 0.7617223 , 0.76741106,
        0.75681669, 0.74799743, 0.75722394, 0.7457834 , 0.71100302,
        0.71027925, 0.7142273 , 0.78053222, 0.7747354 , 0.776799  ,
        0.69274746, 0.69823034, 0.69039816, 0.6990949 , 0.70339161,
        0.70205372],
       [0.79748469, 0.81324299, 0.80684091, 0.78109838, 0.80442568,
        0.79976773, 0.76974595, 0.78386701, 0.77828882, 0.83653322,
        0.84165487, 0.83887311, 0.73356722, 0.75243357, 0.7432468 ,
        0.76160331, 0.77096147, 0.76641833, 0.76389214, 0.77027251,
        0.7676088 , 0.74985302, 0.76056659, 0.75677953, 0.71443954,
        0.71019066, 0.71292529, 0.77815594, 0.77009305, 0.77678844,
        0.6961202 , 0.69885447, 0.69899394, 0.70114397, 0.70368045,
        0.70487511],
      

In [229]:
row_name = ["binary","NCPA","emb","PSNP","ENAC","PseDNC","EIIP","PCP","DBPF"]

In [223]:
header_name=[]
for i in range(12):
    header_name.append(name_no_fold[27*i][:-8])
    header_name.append(name_no_fold[27*i+1][:-8])
    header_name.append(name_no_fold[27*i+2][:-8])

In [224]:
pd.DataFrame(np.append(np.array(header_name).reshape(-1,1),data.T,axis=1)).to_csv("Table/fea_net_cell.csv",header=row_name,index=None)

In [225]:
AUC_no_cell = np.zeros(9*6).reshape(9,6)
for i in range(9):
    for j in range(3):
        AUC_no_cell[i][j] = (data[i][j]+data[i][j+3]+data[i][j+6]+data[i][j+9]+data[i][j+12]+data[i][j+15])/6
        AUC_no_cell[i][j+3] = (data[i][j+18]+data[i][j+21]+data[i][j+24]+data[i][j+27]+data[i][j+30]+data[i][j+33])/6

In [232]:
pd.DataFrame(np.append(np.array(row_name).reshape(-1,1),AUC_no_cell,axis=1)).to_csv("Table/feature_network.csv",header = header_name,index=0)

In [231]:
header_name = ["#","FullTranscript_Self-Attention+BiLSTM","FullTranscript_BILSTM+Self-Attention","FullTranscript_BILSTM",
              "matureRNA_Self-Attention+BiLSTM","matureRNA_BILSTM+Self-Attention","matureRNA_BILSTM"]

# 表2:不同特征，不同模式构表

In [23]:
AUC_no_cell = np.array([[0.78044989, 0.7967157 , 0.77302184, 0.73554214, 0.74163047,
        0.73500879],
       [0.78537678, 0.79877831, 0.79591146, 0.73711679, 0.73963639,
        0.74029554],
       [0.7998955 , 0.8121221 , 0.80273764, 0.7384296 , 0.74618843,
        0.74513795],
       [0.78495357, 0.78453728, 0.78368283, 0.73742559, 0.73868289,
        0.7385597 ],
       [0.77959792, 0.77976204, 0.78403731, 0.7354851 , 0.73531707,
        0.73639035],
       [0.69802114, 0.70266828, 0.69488115, 0.60122892, 0.60597871,
        0.60233149],
       [0.72576409, 0.7335714 , 0.73330189, 0.666836  , 0.66999631,
        0.67003306],
       [0.77498507, 0.77857799, 0.7782328 , 0.68365315, 0.68647034,
        0.68830622],
       [0.79089841, 0.79757488, 0.79763699, 0.73664117, 0.74011017,
        0.73840446]])

In [24]:
##仅仅选取LSTM+Self_Attention作为参考
fea_result = np.zeros(9*2).reshape(9,2)
for i in range(9):
    for j in range(2):
        fea_result[i][j] = AUC_no_cell[i][1+3*j]

In [25]:
fea_result

array([[0.7967157 , 0.74163047],
       [0.79877831, 0.73963639],
       [0.8121221 , 0.74618843],
       [0.78453728, 0.73868289],
       [0.77976204, 0.73531707],
       [0.70266828, 0.60597871],
       [0.7335714 , 0.66999631],
       [0.77857799, 0.68647034],
       [0.79757488, 0.74011017]])

In [26]:
row_name = ["binary","NCPA","emb","PSNP","ENAC","PseDNC","EIIP","PCP","DBPF"]
header_name = ["FullTranscript","matureRNA"]
network = ["BILSTM+Self-Attention"]

# 分析第二阶段不同注意力机制的结果--DBPF特征

In [152]:
DBPF_AUC = np.array(pd.read_csv("First_Second_Result/DBPF_Parameter.csv").iloc[:,-1])
DBPF_name = np.array(pd.read_csv("First_Second_Result/DBPF_Parameter.csv").iloc[:,0])

In [153]:
#对KFold取均值
name_no_fold = []
AUC_no_fold = []
for i in range(len(DBPF_name)):
    if i%5==0:
        AUC_no_fold.append(np.mean(DBPF_AUC[i:i+5]))
        name_no_fold.append(DBPF_name[i][:-8])

In [71]:
name_no_fold

['FullTranscript_A549_DBPF_BILSTM+Self-Attention',
 'FullTranscript_A549_DBPF_BILSTM+MultiSelf-Attention',
 'FullTranscript_A549_DBPF_BILSTM+Bah-Attention',
 'FullTranscript_CD8T_DBPF_BILSTM+Self-Attention',
 'FullTranscript_CD8T_DBPF_BILSTM+MultiSelf-Attention',
 'FullTranscript_CD8T_DBPF_BILSTM+Bah-Attention',
 'FullTranscript_Hek293_abacm_DBPF_BILSTM+Self-Attention',
 'FullTranscript_Hek293_abacm_DBPF_BILSTM+MultiSelf-Attention',
 'FullTranscript_Hek293_abacm_DBPF_BILSTM+Bah-Attention',
 'FullTranscript_Hek293_sysy_DBPF_BILSTM+Self-Attention',
 'FullTranscript_Hek293_sysy_DBPF_BILSTM+MultiSelf-Attention',
 'FullTranscript_Hek293_sysy_DBPF_BILSTM+Bah-Attention',
 'FullTranscript_HeLa_DBPF_BILSTM+Self-Attention',
 'FullTranscript_HeLa_DBPF_BILSTM+MultiSelf-Attention',
 'FullTranscript_HeLa_DBPF_BILSTM+Bah-Attention',
 'FullTranscript_MOLM13_DBPF_BILSTM+Self-Attention',
 'FullTranscript_MOLM13_DBPF_BILSTM+MultiSelf-Attention',
 'FullTranscript_MOLM13_DBPF_BILSTM+Bah-Attention',
 'matur

In [154]:
data = np.zeros(len(AUC_no_fold)).reshape(12,-1)
for i in range(12):
    for j in range(3):
        data[i][j] = AUC_no_fold[j+3*i]

In [158]:
data

array([[0.78250359, 0.77983761, 0.78900835],
       [0.77354184, 0.7698477 , 0.77672936],
       [0.76602997, 0.75837229, 0.77151424],
       [0.81419113, 0.819798  , 0.82547734],
       [0.72342785, 0.73031947, 0.73451602],
       [0.74044012, 0.73826836, 0.74961786],
       [0.75324082, 0.74991761, 0.75381255],
       [0.7398461 , 0.73760197, 0.74157065],
       [0.71736291, 0.71672426, 0.71437547],
       [0.7714969 , 0.77309798, 0.76617868],
       [0.68635233, 0.68836472, 0.68946688],
       [0.69814343, 0.69938631, 0.69740692]])

In [160]:
type_name = ["FullTranscript","matureRNA"]
cell_name = ["A549","CD8T","Hek293_abacm","Hek293_sysy","HeLa","MOLM13"]
row_name = ["Net_name","FullTranscript_A549","FullTranscript_CD8T","FullTranscript_Hek293_abacm","FullTranscript_Hek293_sysy","FullTranscript_HeLa","FullTranscript_MOLM13",
           "matureRNA_A549","matureRNA_CD8T","matureRNA_Hek293_abacm","matureRNA_Hek293_sysy","matureRNA_HeLa","matureRNA_MOLM13"]
header_name = ["BILSTM+Self-Attention","BILSTM+MultiSelf-Attention","BILSTM+Bah-Attention"]

In [161]:
pd.DataFrame(np.append(np.array(header_name).reshape(-1,1),data.T,axis=1)).to_csv("Table/DBPF.csv",header=row_name,index=0)

In [77]:
data_no_cell = np.zeros(2*3).reshape(2,3)
for i in range(2):
    for j in range(3):
        data_no_cell[i][j] = np.mean(data[6*i:6*i+6,j])

In [78]:
row_name = ["FullTranscript","matureRNA"]
header_name = ["BILSTM+Self-Attention","BILSTM+MultiSelf-Attention","BILSTM+Bah-Attention"]
data_no_cell

array([[0.76668908, 0.76607391, 0.7744772 ],
       [0.72774041, 0.72751548, 0.72713519]])

In [115]:
np.array([[0.76668908, 0.76607391, 0.7744772 ],
       [0.72774041, 0.72751548, 0.72713519]]).T

array([[0.76668908, 0.72774041],
       [0.76607391, 0.72751548],
       [0.7744772 , 0.72713519]])

# 分析第二阶段不同注意力机制的结果--emb特征

In [162]:
emb_AUC = np.array(pd.read_csv("First_Second_Result/emb_Parameter.csv").iloc[:,-1])
emb_name = np.array(pd.read_csv("First_Second_Result/emb_Parameter.csv").iloc[:,0])
#对KFold取均值
name_no_fold = []
AUC_no_fold = []
for i in range(len(emb_name)):
    if i%5==0:
        AUC_no_fold.append(np.mean(emb_AUC[i:i+5]))
        name_no_fold.append(emb_name[i][:-8])

In [163]:
data = np.zeros(len(AUC_no_fold)).reshape(12,-1)
for i in range(12):
    for j in range(4):
        data[i][j] = AUC_no_fold[j+4*i]

In [164]:
data

array([[0.82067331, 0.82444505, 0.82338461, 0.81887285],
       [0.81477583, 0.81737109, 0.81580552, 0.81296362],
       [0.79185419, 0.7949792 , 0.79242394, 0.79193947],
       [0.84098322, 0.8420623 , 0.84106901, 0.83855615],
       [0.76794831, 0.77133285, 0.76946454, 0.76488906],
       [0.78471246, 0.78544351, 0.78544698, 0.78206273],
       [0.77344769, 0.77944032, 0.77745042, 0.77371194],
       [0.76430054, 0.76739511, 0.76597989, 0.76296515],
       [0.70872725, 0.70954653, 0.71286605, 0.71008035],
       [0.76753308, 0.76856745, 0.77227696, 0.76425235],
       [0.70728591, 0.71300673, 0.71156896, 0.70561538],
       [0.70456903, 0.70515722, 0.70559123, 0.70534031]])

In [165]:
type_name = ["FullTranscript","matureRNA"]
cell_name = ["A549","CD8T","Hek293_abacm","Hek293_sysy","HeLa","MOLM13"]
row_name = ["Net_name","FullTranscript_A549","FullTranscript_CD8T","Full Transcript_Hek293_abacm","FullTranscript_Hek293_sysy","FullTranscript_HeLa","FullTranscript_MOLM13",
           "matureRNA_A549","matureRNA_CD8T","matureRNA_Hek293_abacm","matureRNA_Hek293_sysy","matureRNA_HeLa","matureRNA_MOLM13"]
header_name = ["BILSTM+Self-Attention","BILSTM+MultiSelf-Attention","BILSTM+Bah-Attention","BILSTM+MultiHead-Attention"]

In [166]:
pd.DataFrame(np.append(np.array(header_name).reshape(-1,1),data.T,axis=1)).to_csv("Table/W2v.csv",header=row_name,index=0)

In [91]:
data_no_cell = np.zeros(2*4).reshape(2,4)
for i in range(2):
    for j in range(4):
        data_no_cell[i][j] = np.mean(data[6*i:6*i+6,j])
row_name = ["FullTranscript","matureRNA"]
header_name = ["BILSTM+Self-Attention","BILSTM+MultiSelf-Attention","BILSTM+Bah-Attention","BILSTM+MultiHead-Attention"]
data_no_cell
#["MultiSelf-Attention"]

array([[0.80349122, 0.805939  , 0.8045991 , 0.80154731],
       [0.73764392, 0.74051889, 0.74095559, 0.73699425]])

In [93]:
np.mean(data[:,0]),np.mean(data[:,1]),np.mean(data[:,2]),np.mean(data[:,3])

(0.7705675673475474,
 0.7732289465130607,
 0.7727773419443279,
 0.7692707809207672)

# 分析第二阶段不同注意力机制的结果--PCP特征

In [167]:
PCP_AUC = np.array(pd.read_csv("First_Second_Result/PCP_Parameter.csv").iloc[:,-1])
PCP_name = np.array(pd.read_csv("First_Second_Result/PCP_Parameter.csv").iloc[:,0])
#对KFold取均值
name_no_fold = []
AUC_no_fold = []
for i in range(len(PCP_name)):
    if i%5==0:
        AUC_no_fold.append(np.mean(PCP_AUC[i:i+5]))
        name_no_fold.append(PCP_name[i][:-8])
data = np.zeros(len(AUC_no_fold)).reshape(12,-1)
for i in range(12):
    for j in range(3):
        data[i][j] = AUC_no_fold[j+3*i]
type_name = ["FullTranscript","matureRNA"]
cell_name = ["A549","CD8T","Hek293_abacm","Hek293_sysy","HeLa","MOLM13"]
row_name = ["Net_name","FullTranscript_A549","FullTranscript_CD8T","FullTranscript_Hek293_abacm","FullTranscript_Hek293_sysy","FullTranscript_HeLa","FullTranscript_MOLM13",
           "matureRNA_A549","matureRNA_CD8T","matureRNA_Hek293_abacm","matureRNA_Hek293_sysy","matureRNA_HeLa","matureRNA_MOLM13"]
header_name = ["BILSTM+Self-Attention","BILSTM+MultiSelf-Attention","BILSTM+Bah-Attention"]
data

array([[0.78699213, 0.78454707, 0.77092574],
       [0.79006605, 0.78536811, 0.76195707],
       [0.77179184, 0.77122212, 0.74477973],
       [0.79399556, 0.79535382, 0.77675894],
       [0.76185324, 0.75524968, 0.73522399],
       [0.76177659, 0.76302969, 0.73912801],
       [0.72024419, 0.72347525, 0.70175763],
       [0.7169541 , 0.71622521, 0.69443562],
       [0.66142304, 0.6538829 , 0.6370712 ],
       [0.68748337, 0.68913069, 0.67054488],
       [0.67532466, 0.68204619, 0.6581267 ],
       [0.65290415, 0.65406223, 0.63425036]])

In [168]:
pd.DataFrame(np.append(np.array(header_name).reshape(-1,1),data.T,axis=1)).to_csv("Table/PCP.csv",header=row_name,index=0)

In [95]:
data_no_cell = np.zeros(2*3).reshape(2,3)
for i in range(2):
    for j in range(3):
        data_no_cell[i][j] = np.mean(data[6*i:6*i+6,j])
row_name = ["FullTranscript","matureRNA"]
header_name = ["BILSTM+Self-Attention","BILSTM+MultiSelf-Attention","BILSTM+Bah-Attention"]
data_no_cell
#["self_Attention"]

array([[0.7777459 , 0.77579508, 0.75479558],
       [0.68572225, 0.68647041, 0.66603107]])

# 分析第二阶段不同注意力机制的结果--PSNP特征

In [98]:
PSNP_AUC = np.array(pd.read_csv("First_Second_Result/PSNP_Parameter.csv").iloc[:,-1])
PSNP_name = np.array(pd.read_csv("First_Second_Result/PSNP_Parameter.csv").iloc[:,0])
#对KFold取均值
name_no_fold = []
AUC_no_fold = []
for i in range(len(PSNP_name)):
    if i%5==0:
        AUC_no_fold.append(np.mean(PSNP_AUC[i:i+5]))
        name_no_fold.append(PSNP_name[i][:-8])
data = np.zeros(len(AUC_no_fold)).reshape(12,-1)
for i in range(12):
    for j in range(3):
        data[i][j] = AUC_no_fold[j+3*i]
type_name = ["FullTranscript","matureRNA"]
cell_name = ["A549","CD8T","Hek293_abacm","Hek293_sysy","HeLa","MOLM13"]
row_name = ["FullTranscript_A549","FullTranscript_CD8T","FullTranscript_Hek293_abacm","FullTranscript_Hek293_sysy","FullTranscript_HeLa","FullTranscript_MOLM13",
           "matureRNA_A549","matureRNA_CD8T","matureRNA_Hek293_abacm","matureRNA_Hek293_sysy","matureRNA_HeLa","matureRNA_MOLM13"]
header_name = ["BILSTM+Self-Attention","BILSTM+MultiSelf-Attention","BILSTM+Bah-Attention"]
data

array([[0.78734857, 0.78816989, 0.77329819],
       [0.77070791, 0.76369823, 0.75896452],
       [0.7717782 , 0.77039646, 0.76258938],
       [0.85259952, 0.84934269, 0.84668586],
       [0.71210298, 0.71903632, 0.71196931],
       [0.74958082, 0.74673766, 0.74565701],
       [0.76024044, 0.76187478, 0.75324461],
       [0.74246659, 0.74555098, 0.7426551 ],
       [0.72235349, 0.71822364, 0.71599319],
       [0.78654818, 0.78785157, 0.78786743],
       [0.68045619, 0.68488863, 0.67970679],
       [0.69879228, 0.70101065, 0.69465429]])

In [99]:
data_no_cell = np.zeros(2*3).reshape(2,3)
for i in range(2):
    for j in range(3):
        data_no_cell[i][j] = np.mean(data[6*i:6*i+6,j])
row_name = ["FullTranscript","matureRNA"]
header_name = ["BILSTM+Self-Attention","BILSTM+MultiSelf-Attention","BILSTM+Bah-Attention"]
data_no_cell
#["MultiSelf_Attention"]

array([[0.77401967, 0.77289688, 0.76652738],
       [0.73180953, 0.73323338, 0.72902023]])

# 分析单独使用Blastn得到的结果

In [339]:
from utils import metricsCal
Th = []
Sen_test = []
Spe_test = []
Acc_test = []
Mcc_test = []
Auc_test = []
type_name = ["FullTranscript","matureRNA"]
cell_name = ["A549","CD8T","Hek293_abacm","Hek293_sysy","HeLa","MOLM13"]
for typei in range(len(type_name)):
    for celli in range(len(cell_name)):
        file_name = "Blastn/" + type_name[typei] + "_"+cell_name[celli]+"_result_train.csv"
        y_pred = np.array(pd.read_csv(file_name,header=None,index_col=0).iloc[:,0])
        y_true = np.array(pd.read_csv(file_name,header=None,index_col=0).iloc[:,1])
        th,_,_,_,_,_,_,_,_,_ = metricsCal.get_train_metrics(y_pred,y_true)
        file_name = "Blastn/" + type_name[typei] + "_"+cell_name[celli]+"_result.csv"
        y_pred = np.array(pd.read_csv(file_name,header=None,index_col=0).iloc[:,0])
        y_true = np.array(pd.read_csv(file_name,header=None,index_col=0).iloc[:,1])
        _,_,_,_,sen,spe,acc,mcc,auc = metricsCal.get_test_metrics(y_pred,y_true,th)
        Sen_test.append(sen)
        Spe_test.append(spe)
        Acc_test.append(acc)
        Mcc_test.append(mcc)
        Auc_test.append(auc)
        Th.append(th)

In [343]:
np.mean(Auc_test[6:12])

0.6711812724858165

In [127]:
A = np.array([row_name,Sen_test,Spe_test,Acc_test,Mcc_test,Auc_test,Th])

In [122]:
header_name = ["#","Sensitivity","Speciality","Accuracy","Mcc","AuROC","Threshold"]
row_name = ["FullTranscript_A549","FullTranscript_CD8T","FullTranscript_Hek293_abacm","FullTranscript_Hek293_sysy","FullTranscript_HeLa","FullTranscript_MOLM13",
           "matureRNA_A549","matureRNA_CD8T","matureRNA_Hek293_abacm","matureRNA_Hek293_sysy","matureRNA_HeLa","matureRNA_MOLM13"]

In [130]:
(pd.DataFrame(A).T).to_csv("Table/Blastn_result.csv",header=header_name,index=0)

# 选取最优特征--包含Blastn与不包含Blastn

In [344]:
data = np.array(pd.read_csv("Stacking_result/Poly_10_Standard.csv"))[:,1:]
row_name = np.array(pd.read_csv("Stacking_result/Poly_10_Standard.csv"))[:,0]
header_name = pd.read_csv("Stacking_result/Poly_10_Standard.csv").columns[1:]

In [345]:
def get_normal_avg(x):
    n = 0 
    sum_x = 0
    for i in x:
        if i>0.55:
            n+=1
            sum_x+=i
    return sum_x/n

In [346]:
data_no_fold = np.zeros(1023*12).reshape(1023,12)
for i in range(len(data)):
    for j in range(12):
        data_no_fold[i][j] = get_normal_avg(data[i][5*j:5*j+5])

In [347]:
def get_n_best(n):
    best_avg = 0
    best_index = -1
    for i in range(len(data_no_fold)):
        if row_name[i].count('_')==n:
            if np.mean(data_no_fold[i])>best_avg:
                best_avg = np.mean(data_no_fold[i])
                best_index = i
    return best_avg,row_name[best_index],best_index

In [349]:
row_best = []
data_best = []
fea_with_blastn = []
for i in range(10):
    best_avg,best_fea,best_index = get_n_best(i)
    fea_with_blastn.append(best_avg)
    print(best_avg,best_fea)
    row_best.append(row_name[best_index])
    data_best.append(data_no_fold[best_index])

0.7740982057094485 emb
0.7794928740301416 DBPF_Blastn
0.7840974307177527 emb_DBPF_Blastn
0.7866428171829322 NCPA_emb_PCP_Blastn
0.7878195384048565 emb_PSNP_PCP_DBPF_Blastn
0.7880296173030604 NCPA_emb_PSNP_PCP_DBPF_Blastn
0.7880897566218975 NCPA_emb_PSNP_PseDNC_PCP_DBPF_Blastn
0.7881373061582262 NCPA_emb_PSNP_PseDNC_EIIP_PCP_DBPF_Blastn
0.7880669411073417 binary_NCPA_emb_PSNP_PseDNC_EIIP_PCP_DBPF_Blastn
0.7879072573098802 binary_NCPA_emb_PSNP_ENAC_PseDNC_EIIP_PCP_DBPF_Blastn


In [350]:
fea_with_blastn

[0.7740982057094485,
 0.7794928740301416,
 0.7840974307177527,
 0.7866428171829322,
 0.7878195384048565,
 0.7880296173030604,
 0.7880897566218975,
 0.7881373061582262,
 0.7880669411073417,
 0.7879072573098802]

In [257]:
header_name = ["fea","FullTranscript_A549","FullTranscript_CD8T","FullTranscript_Hek293_abacm","FullTranscript_Hek293_sysy","FullTranscript_HeLa","FullTranscript_MOLM13",
           "matureRNA_A549","matureRNA_CD8T","matureRNA_Hek293_abacm","matureRNA_Hek293_sysy","matureRNA_HeLa","matureRNA_MOLM13"]

In [258]:
pd.DataFrame(np.append(  np.array(row_best).reshape(-1,1),np.array(data_best),axis=1)).to_csv("Table/fea_select_with_Blastn.csv",header=header_name,index=0)

In [351]:
data = np.array(pd.read_csv("Stacking_result/Poly_9.csv"))[:,1:]
row_name = np.array(pd.read_csv("Stacking_result/Poly_9.csv"))[:,0]
header_name = pd.read_csv("Stacking_result/Poly_9.csv").columns[1:]

In [352]:
data_no_fold = np.zeros(511*12).reshape(511,12)
for i in range(len(data)):
    for j in range(12):
        data_no_fold[i][j] = get_normal_avg(data[i][5*j:5*j+5])

In [353]:
row_best = []
data_best = []
fea =[]
for i in range(9):
    best_avg,best_fea,best_index = get_n_best(i)
    fea.append(best_avg)
    print(best_avg,best_fea)
    row_best.append(row_name[best_index])
    data_best.append(data_no_fold[best_index])

0.7740982098609416 emb
0.7736459253879353 PSNP_PCP
0.7787062792712284 emb_PSNP_PCP
0.7802190128673807 emb_PSNP_PCP_DBPF
0.7804866415541132 NCPA_emb_PSNP_PCP_DBPF
0.7806249680747861 NCPA_emb_PSNP_EIIP_PCP_DBPF
0.7807561955074988 NCPA_emb_PSNP_PseDNC_EIIP_PCP_DBPF
0.7807351183573213 binary_NCPA_emb_PSNP_PseDNC_EIIP_PCP_DBPF
0.780717248757874 binary_NCPA_emb_PSNP_ENAC_PseDNC_EIIP_PCP_DBPF


In [354]:
fea

[0.7740982098609416,
 0.7736459253879353,
 0.7787062792712284,
 0.7802190128673807,
 0.7804866415541132,
 0.7806249680747861,
 0.7807561955074988,
 0.7807351183573213,
 0.780717248757874]

In [265]:
header_name = ["fea","FullTranscript_A549","FullTranscript_CD8T","FullTranscript_Hek293_abacm","FullTranscript_Hek293_sysy","FullTranscript_HeLa","FullTranscript_MOLM13",
           "matureRNA_A549","matureRNA_CD8T","matureRNA_Hek293_abacm","matureRNA_Hek293_sysy","matureRNA_HeLa","matureRNA_MOLM13"]
pd.DataFrame(np.append(np.array(row_best).reshape(-1,1),np.array(data_best),axis=1)).to_csv("Table/fea_select_without_Blastn.csv",header=header_name,index=0)

# 与其他模型对比 LA6mA、DeepM6ASeq-EL

In [ ]:
####LA6mA

In [448]:
data = np.array(pd.read_csv("Table/result_LA6mA_All.csv").iloc[:,1:-1])
header_name = ["name",'Sen', 'Spe', 'Acc', 'Mcc', 'Auc']

In [443]:
result_LA6mA = np.zeros(12*5).reshape(12,5)
for i in range(12):
    result_LA6mA[i][0] = np.mean(data[5*i:5*i+5,0])
    result_LA6mA[i][1] = np.mean(data[5*i:5*i+5,1])
    result_LA6mA[i][2] = np.mean(data[5*i:5*i+5,2])
    result_LA6mA[i][3] = np.mean(data[5*i:5*i+5,3])
    result_LA6mA[i][4] = np.mean(data[5*i:5*i+5,4])

In [449]:
pd.DataFrame(np.append(np.array(row).reshape(-1,1),np.array(result_LA6mA),axis=1)).to_csv("Table/result_LA6mA.csv",header=header_name,index=0)

In [291]:
row = []
header_name = ["name","Acc","Mcc","Auc"]
result_LA6mA = np.zeros(12*3).reshape(12,3)
for i in range(12):
    row.append(row_name[5*i][:-15])
    result_LA6mA[i][0] = np.mean(acc[5*i:5*i+5])
    result_LA6mA[i][1] = np.mean(mcc[5*i:5*i+5])
    result_LA6mA[i][2] = np.mean(auc[5*i:5*i+5])

In [292]:
pd.DataFrame(np.append(np.array(row).reshape(-1,1),np.array(result_LA6mA),axis=1)).to_csv("Table/result_LA6mA.csv",header=header_name,index=0)

In [301]:
####DeepM6ASeq-EL

In [310]:
row = np.array(pd.read_csv("DeepM6ASeq-EL/result_All_DeepM6ASeq-EL.csv").iloc[:,0])
data = np.array(pd.read_csv("DeepM6ASeq-EL/result_All_DeepM6ASeq-EL.csv").iloc[:,1:])

In [311]:
row_name = []
header_name = ["name","Sen","Spe","Acc","Mcc","Auc"]
result_m6A_EL = np.zeros(12*5).reshape(12,5)
for i in range(12):
    row_name.append(row[5*i][:-7])
    result_m6A_EL[i][0] = np.mean(data[5*i:5*i+5,0])
    result_m6A_EL[i][1] = np.mean(data[5*i:5*i+5,1])
    result_m6A_EL[i][2] = np.mean(data[5*i:5*i+5,2])
    result_m6A_EL[i][3] = np.mean(data[5*i:5*i+5,3])
    result_m6A_EL[i][4] = np.mean(data[5*i:5*i+5,4])

In [316]:
pd.DataFrame(np.append(np.array(row_name).reshape(-1,1),np.array(result_m6A_EL),axis=1)).to_csv("Table/result_DeepM6ASeq-EL.csv",header=header_name,index=0)

In [369]:
np.mean(pd.read_csv("Table/result_DeepM6ASeq-EL.csv").iloc[:,-1])

0.7630136739654462

In [452]:
####Bert6mA
#row = np.array(pd.read_csv("BERT6mA/Auc_BERT6mA.csv").iloc[:,0])
data = np.array(pd.read_csv("BERT6mA/result_BERT.csv").iloc[:,1:-1])

In [453]:
result_Bert6mA = np.zeros(12*5).reshape(12,5)
for i in range(12):
    result_Bert6mA[i][0] = np.mean(data[5*i:5*i+5,0])
    result_Bert6mA[i][1] = np.mean(data[5*i:5*i+5,1])
    result_Bert6mA[i][2] = np.mean(data[5*i:5*i+5,2])
    result_Bert6mA[i][3] = np.mean(data[5*i:5*i+5,3])
    result_Bert6mA[i][4] = np.mean(data[5*i:5*i+5,4])

In [455]:
pd.DataFrame(np.append(np.array(row).reshape(-1,1),np.array(result_Bert6mA),axis=1)).to_csv("Table/result_Bert6mA.csv",header=header_name,index=0)

In [465]:
###DeepM6ASeq
Sen = pd.read_csv("DeepM6ASeq/Sen_DeepM6ASeq.csv").iloc[:,-1]
Spe = pd.read_csv("DeepM6ASeq/Spe_DeepM6ASeq.csv").iloc[:,-1]
Acc = pd.read_csv("DeepM6ASeq/Acc_DeepM6ASeq.csv").iloc[:,-1]
Mcc = pd.read_csv("DeepM6ASeq/Mcc_DeepM6ASeq.csv").iloc[:,-1]
Auc = pd.read_csv("DeepM6ASeq/Auc_DeepM6ASeq.csv").iloc[:,-1]
result_DeepM6ASeq = np.zeros(12*5).reshape(12,5)
for i in range(12):
    result_DeepM6ASeq[i][0] = np.mean(Sen[5*i:5*i+5])
    result_DeepM6ASeq[i][1] = np.mean(Spe[5*i:5*i+5])
    result_DeepM6ASeq[i][2] = np.mean(Acc[5*i:5*i+5])
    result_DeepM6ASeq[i][3] = np.mean(Mcc[5*i:5*i+5])
    result_DeepM6ASeq[i][4] = np.mean(Auc[5*i:5*i+5])

In [467]:
pd.DataFrame(np.append(np.array(row).reshape(-1,1),np.array(result_DeepM6ASeq),axis=1)).to_csv("Table/result_DeepM6ASeq.csv",header=header_name,index=0)

In [456]:
###LAMB-merge
data = np.array(pd.read_csv("Table/Stacking_Result.csv").iloc[:,1:-1])
result_LAM = np.zeros(12*5).reshape(12,5)
for i in range(12):
    result_LAM[i][0] = np.mean(data[5*i:5*i+5,0])
    result_LAM[i][1] = np.mean(data[5*i:5*i+5,1])
    result_LAM[i][2] = np.mean(data[5*i:5*i+5,2])
    result_LAM[i][3] = np.mean(data[5*i:5*i+5,3])
    result_LAM[i][4] = np.mean(data[5*i:5*i+5,4])

In [496]:
np.mean(result_LAM[0:6,-1])

0.848795759834189

In [460]:
pd.DataFrame(np.append(np.array(row).reshape(-1,1),np.array(result_LAM),axis=1)).to_csv("Table/result_LAM.csv",header=header_name,index=0)

# 多模态特征融合策略对比

In [411]:
###中期Attention层融合
Auc = np.array(pd.read_csv("Model_Fusion_Extraction_Final/Auc_Mid.csv").iloc[:,-1])
ROW = np.array(pd.read_csv("Model_Fusion_Extraction_Final/Auc_Mid.csv").iloc[:,0])

In [412]:
row = []
Auc_attn_Fusion = np.zeros(12).reshape(12,1)
for i in range(12):
    row.append(ROW[5*i][:-19])
    Auc_attn_Fusion[i][0] = np.mean(Auc[5*i:5*i+5])

In [413]:
np.mean(Auc_attn_Fusion)

0.763632664062134

In [360]:
###中期Fn层融合
Auc = np.array(pd.read_csv("Model_Fusion_Extraction_Final/Auc_MidFn.csv").iloc[:,-1])
Auc_Fn_Fusion = np.zeros(12).reshape(12,1)
for i in range(12):
    Auc_Fn_Fusion[i][0] = np.mean(Auc[5*i:5*i+5])

In [362]:
np.mean(Auc_Fn_Fusion)

0.772522396894047

In [364]:
###早期特征融合
Auc = np.array(pd.read_csv("Model_Fusion_Extraction_Final/Auc_Early.csv").iloc[:,-1])
Auc_Early_Fusion = np.zeros(12).reshape(12,1)
for i in range(12):
    Auc_Early_Fusion[i][0] = np.mean(Auc[5*i:5*i+5])

In [365]:
np.mean(Auc_Early_Fusion)

0.7786235125399781

In [378]:
###后期融合软投票
Auc = np.array(pd.read_csv("Table/Soft_Voting_result.csv"))[:,-2]
Auc_Soft_Voting_Fusion = np.zeros(12).reshape(12,1)
for i in range(12):
    Auc_Soft_Voting_Fusion[i][0] = np.mean(Auc[5*i:i*5+5])

In [400]:
###后期融合硬投票
Auc = np.array(pd.read_csv("Table/Hard_Voting_result_iter_0.3_0.7.csv").iloc[:,-2])
Auc_Hard_Voting_Fusion = np.zeros(12).reshape(12,1)
for i in range(12):
    Auc_Hard_Voting_Fusion[i][0] = np.mean(Auc[5*i:i*5+5])

In [404]:
###后期融合堆叠策略
Auc = np.array(pd.read_csv("Table/Stacking_Result_no_Blastn.csv").iloc[:,-2])
Auc_Stacking_Fusion = np.zeros(12).reshape(12,1)
for i in range(12):
    Auc_Stacking_Fusion[i][0] = np.mean(Auc[5*i:i*5+5])

In [405]:
###后期融合堆叠策略 带Blastn
Auc = np.array(pd.read_csv("Table/Stacking_Result.csv").iloc[:,-2])
Auc_Stacking_Blastn_Fusion = np.zeros(12).reshape(12,1)
for i in range(12):
    Auc_Stacking_Blastn_Fusion[i][0] = np.mean(Auc[5*i:i*5+5])

In [420]:
row_name = ["Early","Attn_Fusion","Fn_Fusion","Hard_Voting","Soft_Voting","Stacking","Stacking_With_Blastn"]

In [421]:
header_name = ["name",'FullTranscript_A549', 'FullTranscript_CD8T', 'FullTranscript_Hek293_abacm',
 'FullTranscript_Hek293_sysy', 'FullTranscript_HeLa', 'FullTranscript_MOLM13',
 'matureRNA_A549', 'matureRNA_CD8T', 'matureRNA_Hek293_abacm',
 'matureRNA_Hek293_sysy', 'matureRNA_HeLa', 'matureRNA_MOLM13']

In [429]:
data = np.concatenate((Auc_Early_Fusion,Auc_attn_Fusion,Auc_Fn_Fusion,Auc_Hard_Voting_Fusion,Auc_Soft_Voting_Fusion,Auc_Stacking_Fusion,Auc_Stacking_Blastn_Fusion), axis=1).T

In [432]:
pd.DataFrame(np.append(np.array(row_name).reshape(-1,1),data,axis=1)).to_csv("Table/Fusion_Result.csv",header=header_name,index=0)

# 补充表S3

In [ ]:
DeepM6ASeq-EL
LA6mA
BERT6mA
DeepM6ASeq
BLAM6A-Merge


In [488]:
data_DeepM6ASeq_EL = np.array(pd.read_csv("Table/result_DeepM6ASeq-EL.csv").iloc[:,1:])

In [489]:
data_LA6mA = np.array(pd.read_csv("Table/result_LA6mA.csv").iloc[:,1:])
data_Bert6mA = np.array(pd.read_csv("Table/result_Bert6mA.csv").iloc[:,1:])
data_DeepM6ASeq = np.array(pd.read_csv("Table/result_DeepM6ASeq.csv").iloc[:,1:])
data_BLAM6A_Merge = np.array(pd.read_csv("Table/result_LAM.csv").iloc[:,1:])

In [490]:
result_All = np.zeros(60*5).reshape(60,5)
for i in range(12):
    for j in range(5):
        result_All[5*i,j] = data_DeepM6ASeq_EL[i,j]
        result_All[5*i+1,j] = data_LA6mA[i,j]
        result_All[5*i+2,j] = data_Bert6mA[i,j]
        result_All[5*i+3,j] = data_DeepM6ASeq[i,j]
        result_All[5*i+4,j] = data_BLAM6A_Merge[i,j]

In [492]:
pd.DataFrame(result_All).to_csv("Table/result_All.csv",header=["Sen","Spe","Acc","Mcc","Auc"])